version: "3"
services:
  database:
    image: mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=bookstore

    volumes:
      - data:/var/lib/mysql



  bookstore:
    build: .
#    restart: always
    environment:
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/bookstore
      - ADMIN_PASSWORD= 12345678 # you have to remove the password and email after the colon from the application file to make this take effect
      - ADMIN_EMAIL= admin@gmail.com
    depends_on:
      - database

    ports:
      - 8080:8080

volumes:
  data:

